# Linear Algebra

## matrix creation and operation

In [1]:
# matrices
import numpy as np
A = np.array([[1,  4,  5, 12],
              [-5, 8,  9,  0],
              [-6, 7, 11, 19]])

In [2]:
# row access
A[0], A[-1]

(array([ 1,  4,  5, 12]), array([-6,  7, 11, 19]))

In [3]:
# column access
A[:,0], A[:,-1]

(array([ 1, -5, -6]), array([12,  0, 19]))

In [4]:
# matrix can also be made by stacking 1-D arrays
v1 = np.array([0, 1, 2])
v2 = np.array([3, 4, 5])
v3 = np.array([6, 7, 8])
v4 = np.array([3, 3, 3])

In [5]:
# 2-d arrays
v11 = np.array([[0, 1, 2]])
v22 = np.array([[3, 4, 5]])
v33 = np.array([[6, 7, 8]])
v44 = np.array([[3, 3, 3]])

In [6]:
np.vstack([v1, v2, v3]), np.vstack([v11, v22, v33])

(array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]),
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]))

In [7]:
np.hstack([v1, v2, v3]), np.hstack([v11, v22, v33])

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]), array([[0, 1, 2, 3, 4, 5, 6, 7, 8]]))

- concatenate arrays
  - very useful for quickly constructing arrays in a concise and readable manner.
  - np.r_[ ]: Concatenates arrays along the row axis (axis 0).
  - np.c_[ ]: Concatenates arrays along the column axis (axis 1).

In [8]:
# 1-d arrays
np.r_[v1, v2, v3], np.r_[v11, v22, v33]

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 array([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]))

In [9]:
np.c_[v1, v2, v3], np.c_[v11.T, v22.T, v33.T]

(array([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]]),
 array([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]]))

- matrix multiplication

In [10]:
M = np.vstack([v1, v2, v3]); M

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [11]:
v4, v44, v4.shape, v44.shape

(array([3, 3, 3]), array([[3, 3, 3]]), (3,), (1, 3))

In [12]:
M.dot(v4) , np.dot(M, v4), M@v4     # dot multiplication

(array([ 9, 36, 63]), array([ 9, 36, 63]), array([ 9, 36, 63]))

In [13]:
try:
    M.dot(v44)
except:
    print('Error')


Error


In [14]:
v4.T, v44.T, v4 == v4.T

(array([3, 3, 3]),
 array([[3],
        [3],
        [3]]),
 array([ True,  True,  True]))

In [15]:
M.dot(v4.T), v4.T.dot(M), v4.dot(M)

(array([ 9, 36, 63]), array([27, 36, 45]), array([27, 36, 45]))

In [16]:
np.dot(M,v4),  np.dot(M,v4.T), np.dot(v4,M), np.dot(v4.T,M)    # equivalent to the above

(array([ 9, 36, 63]),
 array([ 9, 36, 63]),
 array([27, 36, 45]),
 array([27, 36, 45]))

In [17]:
v4, v4.shape, v4.T.shape

(array([3, 3, 3]), (3,), (3,))

In [18]:
np.multiply(M,[1,2,3]), np.multiply(v4,v4)   # element-wise multiplication (and broadcasting)

(array([[ 0,  2,  6],
        [ 3,  8, 15],
        [ 6, 14, 24]]),
 array([9, 9, 9]))

In [19]:
np.multiply(M,[[1],[2],[3]])

array([[ 0,  1,  2],
       [ 6,  8, 10],
       [18, 21, 24]])

In [20]:
np.linalg.det(M)     # determinant

np.float64(0.0)

In [21]:
M =np.array([[1, -1, 0],
             [2, 0, -1],
             [1, 2, -1]])

In [22]:
M_inv = np.linalg.inv(M); M_inv

array([[ 2., -1.,  1.],
       [ 1., -1.,  1.],
       [ 4., -3.,  2.]])

In [23]:
M_inv.dot(M), M.dot(M_inv)

(array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))

In [24]:
M = np.array([[1,0],
              [0,1]])
M

array([[1, 0],
       [0, 1]])

In [25]:
np.linalg.inv(M), np.linalg.pinv(M)  # pseudo inverse (generalized inverse using its SVD)
                                     # useful when the matrix is singular (non-invertible)

(array([[1., 0.],
        [0., 1.]]),
 array([[1., 0.],
        [0., 1.]]))

- pseudo-inverse of A (A+)
  - either A\*A+ or A+\*A is close to I depending on the shape of the matrix

In [26]:
A = np.array([[1, 0],
              [2,-1],
              [1, 1]])
try:
    np.linalg.inv(A)
except:
    print("Error: singular matrix. Trying pinv() instead")
    A_pinv = np.linalg.pinv(A)
    print (A_pinv)

Error: singular matrix. Trying pinv() instead
[[ 0.18181818  0.27272727  0.27272727]
 [ 0.09090909 -0.36363636  0.63636364]]


In [27]:
np.dot (A, A_pinv), np.dot (A_pinv, A)  # these are not the same
                                        # if A is a tall matrix,
                                        # A_pinv*A is close to the Identity matrix.

(array([[ 0.18181818,  0.27272727,  0.27272727],
        [ 0.27272727,  0.90909091, -0.09090909],
        [ 0.27272727, -0.09090909,  0.90909091]]),
 array([[ 1.00000000e+00,  5.55111512e-17],
        [-1.11022302e-16,  1.00000000e+00]]))

In [28]:
B = [[1,2,3],
     [1,5,7]]
np.dot (B, np.linalg.pinv(B))      # if A is a wide matrix,
                                   # A*A_pinv is close to the Identity matrix.

array([[ 1.00000000e+00, -5.13478149e-16],
       [-3.05311332e-16,  1.00000000e+00]])

## Eigen values, eigen vectors

In [29]:
## A.v = lambda.v
A = np.array([[ 0., 1.],
              [-2.,-3.]])
eigvals, eigvecs = np.linalg.eig(A)
print(eigvals, "\n",  eigvecs)

[-1. -2.] 
 [[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]


In [30]:
eigvals[0]*eigvecs[:,0], A.dot(eigvecs[:,0])  # A * v = lambda * v

(array([-0.70710678,  0.70710678]), array([-0.70710678,  0.70710678]))

In [31]:
eigvals[1]*eigvecs[:,1], A.dot(eigvecs[:,1])

(array([ 0.89442719, -1.78885438]), array([ 0.89442719, -1.78885438]))

## LU decomposition

- A is nxn matrix or mxn matrix
- A = LU or PLU (more compuataionally stable)
- L is the lower triangle matrix and U is the upper triangle matrix

In [32]:
import numpy as np
from scipy.linalg import lu, lu_factor

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
# LU decomposition
# PLU decomposition: The rows of the parent matrix are re-ordered to simplify the
# decomposition process and the additional P matrix specifies a way to permute the
# result or return the result to the original order
P, L, U = lu(A)         # LU with partial pivoting (PLU decomposition)
print(P, "\n")
print(L.round(2), "\n")
print(U.round(2), "\n")

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]] 

[[1.   0.   0.  ]
 [0.14 1.   0.  ]
 [0.57 0.5  1.  ]] 

[[7.   8.   9.  ]
 [0.   0.86 1.71]
 [0.   0.   0.  ]] 



In [33]:
# reconstruct
B = P.dot(L).dot(U)
print(B)
L.dot(U)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


array([[7., 8., 9.],
       [1., 2., 3.],
       [4., 5., 6.]])

In [34]:
P_inv = np.linalg.inv(P)

In [35]:
P_inv.dot(A)   # A = P.L.U  --> P_inv.A = L.U

array([[7., 8., 9.],
       [1., 2., 3.],
       [4., 5., 6.]])

In [36]:
# mxn matrix
A = np.array([[1,  3,  2, 0],
              [3, 10,  5, 1],
              [0, -1,  2, 1]])
P, L, U = lu(A)
print(P, "\n")
print(L.round(2), "\n")
print(U.round(2), "\n")

[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]] 

[[1.   0.   0.  ]
 [0.   1.   0.  ]
 [0.33 0.33 1.  ]] 

[[ 3.   10.    5.    1.  ]
 [ 0.   -1.    2.    1.  ]
 [ 0.    0.   -0.33 -0.67]] 



In [37]:
 P.dot(L).dot(U)

array([[ 1.,  3.,  2.,  0.],
       [ 3., 10.,  5.,  1.],
       [ 0., -1.,  2.,  1.]])

## QR decomposition
- Factor the matrix a as qr, where q is orthogonal (orthonormal columns) and r is upper-triangular.
- A; any mxn matrix
- A = QR
- Q is an m x m orthoginal matrix, and R is an upper triangle matrix with the size m x n
- modes:
  - reduced mode: suitable for compact representation and reconstruction of A (Q: orthogonal columns)
  - complete mode: provides a full orthonormal basis for the space spanned by the rows of A (Q: full orthogonal basis)

In [38]:
# QR decomposition

from numpy.linalg import qr

A = np.array([[1, 2],
           [3, 4],
           [5, 6]])  # 3 x 2 matrix

# QR decomposition
Q, R = qr(A)           # default mode = "reduced"
print(Q.round(2), "\n")
print(R.round(2))

[[-0.17  0.9 ]
 [-0.51  0.28]
 [-0.85 -0.35]] 

[[-5.92 -7.44]
 [ 0.    0.83]]


In [39]:
Q@R

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

- 리듀스드 모드는 당면 문제(예: 최소 제곱법)를 푸는 데 필수적인 벡터들만 계산하여 Q 행렬(m x n)을 만든다. 반면 컴플리트 모드는 여기에 추가로 수학적으로 완전한 공간을 만들기 위한 m-n개의 직교 벡터를 더 계산하여 Q 행렬을 정방행렬(m x m)으로 '완성'한다.
- 대부분의 데이터 과학 응용에서는 계산량과 메모리 사용량 면에서 훨씬 효율적인 리듀스드 모드가 기본으로 사용된다.

In [40]:
Q_complete, R_complete = qr(A, mode='complete')       # complete’ : returns q, r with dimensions (M, M), (M, N)
print(Q_complete.round(2), "\n")
print(R_complete.round(2))

[[-0.17  0.9   0.41]
 [-0.51  0.28 -0.82]
 [-0.85 -0.35  0.41]] 

[[-5.92 -7.44]
 [ 0.    0.83]
 [ 0.    0.  ]]


In [41]:
# reconstruct
Q_complete.dot(R_complete)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [42]:
# check orthonormality (orthogonal + normal)
for i in range(3):
    print(np.sqrt ((Q_complete[:,i]**2).sum()))

for i in range(3):
    for j in range(i+1, 3):
        print((Q_complete[:,i] * Q_complete[:,j]).sum())

1.0
1.0
1.0
5.551115123125783e-17
1.6653345369377348e-16
0.0


In [43]:
# check orthogonal matrix (Q@Q.T = Q.T@Q = I)
Q_complete.T @ Q_complete

array([[1.00000000e+00, 6.18439648e-17, 1.45536841e-16],
       [6.18439648e-17, 1.00000000e+00, 1.27605396e-17],
       [1.45536841e-16, 1.27605396e-17, 1.00000000e+00]])

In [44]:
np.allclose(Q_complete.T, np.linalg.inv(Q_complete)) # Q.T = Q_{-1}

True

## Eigen-decomposition
- A = P.D.P^{-1}
- all n x n matrices
- if A is symmetric -> eigenvectors are orthogonal -> A = P.D.P^{-1} = P.D.P^T

In [45]:
# non-symmetric matrix
A = [[1,2],
     [3,4]]
eigvals, eigvecs = np.linalg.eig(A)
print(eigvals)
print(eigvecs)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [46]:
np.dot(eigvecs[:,0],eigvecs[:,1])  # not orthogonal (A_inv != A.T)

np.float64(-0.17149858514250893)

In [47]:
P = eigvecs
print(P.dot(np.diag(eigvals)).dot(np.linalg.inv(P)))   # A =  P.D.P^{-1}
print(P.dot(np.diag(eigvals)).dot(P.T))                # A != P.D.P^T

[[1. 2.]
 [3. 4.]]
[[0.67647059 2.20588235]
 [2.20588235 4.32352941]]


In [48]:
# symmetric matrix
A = np.array([[6,2],
              [2,3]])
eigvals, eigvecs = np.linalg.eig(A)  # v1=eigvecs[:,0], v2=eigvecs[:,1]
print(eigvals)
print(eigvecs)

[7. 2.]
[[ 0.89442719 -0.4472136 ]
 [ 0.4472136   0.89442719]]


In [49]:
np.dot(eigvecs[:,0],eigvecs[:,1])  # eigenvectors are orthogonal

np.float64(0.0)

In [50]:
# reconstruct
P = eigvecs
D = np.diag(eigvals)
print(P.dot(D).dot(np.linalg.inv(P)))   # A =  P.D.P^{-1}
print(P.dot(D).dot(P.T))                # A = P.D.P^T

[[6. 2.]
 [2. 3.]]
[[6. 2.]
 [2. 3.]]


- So far, we know
  - A is not symmstric, A = P.D.P^{-1}
  - A is symmetric, eigenvectors are orthogonal (P^{-1}=P^T), A = P.D.P^{-1} = P.D.P^T

In [51]:
# one more example
A = np.array([[1,0],
              [6,-1]])
eigvals, eigvecs = np.linalg.eig(A)  # v1=eigvecs[:,0], v2=eigvecs[:1]
print(eigvals, "\n",eigvecs)

[-1.  1.] 
 [[0.         0.31622777]
 [1.         0.9486833 ]]


In [52]:
# reconstruct
P, D = eigvecs, np.diag(eigvals)
(P).dot(D).dot(np.linalg.inv(P))

array([[ 1.,  0.],
       [ 6., -1.]])

## SVD (singular value decomposition)
- A = U.S.VT
- U,V are orthogonal matrices (UT=U^−1 and VT=V^−1)
- S is a diagonal matrix (all 0 except the diagonal).
- However S is not necessarily square.
- The columns of U are called the left-singular vectors of A, while the columns of V are the right-singular vectors of A.
- The values along the diagonal of S are the singular values of A.

In [53]:
A = np.array([[1, 2],
           [3, 4],
           [5, 6]])  # 3 x 2 matrix
U, S, VT = np.linalg.svd(A)
Smat = np.diag(S)
Smat = np.vstack([Smat,[0,0]])
print(U,"\n\n", Smat, "\n\n" ,VT)

[[-0.2298477   0.88346102  0.40824829]
 [-0.52474482  0.24078249 -0.81649658]
 [-0.81964194 -0.40189603  0.40824829]] 

 [[9.52551809 0.        ]
 [0.         0.51430058]
 [0.         0.        ]] 

 [[-0.61962948 -0.78489445]
 [-0.78489445  0.61962948]]


In [54]:
print(S)   # singular values
print(np.diag(S))

[9.52551809 0.51430058]
[[9.52551809 0.        ]
 [0.         0.51430058]]


In [55]:
# reconstruct
U.dot(Smat).dot(VT)

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [56]:
# check orthonormality
print(U.shape, VT.shape)

for i in range(U.shape[0]):
    print(np.sqrt ((U[:,i]**2).sum()))

for i in range(U.shape[0]):
    for j in range(i+1, 3):
        print((U[:,i] * U[:,j]).sum())

V = VT.T
for i in range(V.shape[0]):
    print(np.sqrt ((V[:,i]**2).sum()))

for i in range(V.shape[0]):
    for j in range(i+1, 2):
        print((V[:,i] * V[:,j]).sum())

(3, 3) (2, 2)
1.0
1.0
1.0
5.551115123125783e-17
5.551115123125783e-17
0.0
0.9999999999999999
0.9999999999999999
0.0


# A sample for SVD and PCA
- from https://stackoverflow.com/questions/61386915/different-results-with-pca-and-svd-on-data-with-same-units

In [57]:
import numpy as np
from scipy.linalg import svd   # more control over the SVD process than linalg.svd
from sklearn.preprocessing import StandardScaler

X = np.array([[13.71, 1.86, 2.36, 16.6],
              [12.22, 1.29, 1.94, 19.],
              [13.27, 4.28, 2.26, 20.],
              [13.16, 3.57, 2.15, 21.],
              [13.86, 1.51, 2.67, 25.]])
sc = StandardScaler()
X_std = sc.fit_transform(X)

- X_T.X = V(S_T.S)V_T
- Cov = 1/(n-1)*X_T.X (covariance matrix)
- So, square of singular values of X = (n-1) * eigenvalues of Cov

- covariance matrix

In [58]:
# the matrix with raw data
print(np.cov(X, rowvar=False).round(2))  # rows are observations, columns are features

Xs = X - X.mean(axis=0)                 # centered
np.round(Xs.T.dot(Xs)/(len(Xs)-1), 2)   # the same as the above (covariance matrix)

[[ 0.41  0.07  0.16  0.61]
 [ 0.07  1.79 -0.05 -0.12]
 [ 0.16 -0.05  0.07  0.47]
 [ 0.61 -0.12  0.47  9.51]]


array([[ 0.41,  0.07,  0.16,  0.61],
       [ 0.07,  1.79, -0.05, -0.12],
       [ 0.16, -0.05,  0.07,  0.47],
       [ 0.61, -0.12,  0.47,  9.51]])

In [59]:
# the matrix with standard scaled data (already centered)
np.cov(X_std, rowvar=False).round(2), \
np.round(np.dot(X_std.T, X_std)/(len(X_std) - 1), 2)  # the same as the above

(array([[ 1.25,  0.1 ,  1.15,  0.38],
        [ 0.1 ,  1.25, -0.17, -0.04],
        [ 1.15, -0.17,  1.25,  0.71],
        [ 0.38, -0.04,  0.71,  1.25]]),
 array([[ 1.25,  0.1 ,  1.15,  0.38],
        [ 0.1 ,  1.25, -0.17, -0.04],
        [ 1.15, -0.17,  1.25,  0.71],
        [ 0.38, -0.04,  0.71,  1.25]]))

- The eigenvalues of XT*X are the squares of the singular values of X, i.e.
  - XT.X = (USVT)^T . (USVT) = V(ST.S)VT
- Xc = np.dot(X.T,X)/(n-1)  # covariance
- eigen_value(Xc) * (n-1) = singular_value(X)**2

In [60]:
# PCA (X should be centered around zero -> X_std)

cov_mat = np.cov(X_std.T)                           # 1/(n-1)*dot(XT,X) is a covariance matrix
eigen_vals, eigen_vecs = np.linalg.eigh(cov_mat)    # eigh is faster, but only for symmetrics matrix

# SVD
U, singular_vals, VT = svd(X_std)

print('Eig of Cov * (n-1):\t {}'.format(eigen_vals[::-1]*(5-1)))   # from cov of X
print('Singular value **2: \t {}'.format(singular_vals**2))         # from SVD

Eig of Cov * (n-1):	 [11.1732417   5.13574315  3.61254937  0.07846578]
Singular value **2: 	 [11.1732417   5.13574315  3.61254937  0.07846578]


## Coordinate Format and CSC(compressed sparse column)

In [61]:
# create using (data, ij) tuple:
from scipy import sparse

row = np.array([1,3,2,0,3,1])
col = np.array([0,0,1,2,2,3])
data = np.array([2,4,1,3,1,1])
mtx = sparse.csc_matrix((data, (row, col)), shape=(4, 4))
print(mtx)
print(mtx.todense())
print(mtx.data, mtx.indices, mtx.indptr)

<Compressed Sparse Column sparse matrix of dtype 'int64'
	with 6 stored elements and shape (4, 4)>
  Coords	Values
  (1, 0)	2
  (3, 0)	4
  (2, 1)	1
  (0, 2)	3
  (3, 2)	1
  (1, 3)	1
[[0 0 3 0]
 [2 0 0 1]
 [0 1 0 0]
 [4 0 1 0]]
[2 4 1 3 1 1] [1 3 2 0 3 1] [0 2 3 5 6]


In [62]:
# create using (data, indices, indptr) tuple:
# row indices for column i are stored in indices[indptr[i]:indptr[i+1]]

data = np.array([2,4,1,3,1,1])
indices = np.array([1,3,2,0,3,1])
indptr = np.array([0, 2, 3, 5, 6])   # 2개, 1개, 2개, 1개
mtx = sparse.csc_matrix((data, indices, indptr), shape=(4, 4))
mtx.todense()

matrix([[0, 0, 3, 0],
        [2, 0, 0, 1],
        [0, 1, 0, 0],
        [4, 0, 1, 0]])

## image reconstruction using SVD
- from https://cmdlinetips.com/2020/01/image-reconstruction-using-singular-value-decomposition-svd-in-python/

In [63]:
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
from PIL import Image
import seaborn as sns

In [64]:
# my_file = "1092px-5_Boroughs_Labels_New_York_City_Map.svg.png"
my_file = "640px-Above_Gotham.jpg"
img = Image.open(my_file)

plt.imshow(img)

FileNotFoundError: [Errno 2] No such file or directory: '640px-Above_Gotham.jpg'

In [ ]:
img.size   # (width, height)

In [ ]:
# extract red component of the image
red_band =img.getdata(band=0)   # return flattened
# convert to numpy array
img_arr = np.array(list(red_band), float)
img_arr.shape

In [ ]:
img_arr = img_arr.reshape(img.size[1], img.size[0])  # (height, width)
print(img_arr.shape)
plt.imshow(img_arr)

- just for your reference (in case you want to convert it into greyscale)

In [ ]:
# or, convert it into greyscale
import matplotlib.image as mpimg
from PIL import Image

ny_file2 = "640px-Above_Gotham.jpg"

# - direct calculation-
# def rgb2gray(rgb):
#     return np.dot(rgb[...,:3], [0.2989, 0.5870, 0.1140])
#
# img = mpimg.imread(ny_file2)
# gray = rgb2gray(img)

# - or, use PIL.Image -
gray = Image.open(ny_file2).convert('L')

fig, axs = plt.subplots(1, 2, figsize=(20,20))
axs[0].imshow(img)
axs[1].imshow(gray, cmap=plt.get_cmap('gray'))
plt.show()

In [ ]:
fig, axs = plt.subplots(1, 2,figsize=(10,10))
axs[0].imshow(img)
axs[0].set_title('Original Image', size=16)
axs[1].imshow(img_arr)
axs[1].set_title(' "R" band image', size=16)
plt.tight_layout()
plt.savefig('Original_image_and_R_band_image_for_SVD.jpg',dpi=150)

In [ ]:
# Let us center and scale the data before applying SVD. This will help us put
# each variable in the same scale.
# scale the image matrix before SVD
img_arr_scaled=  (img_arr-img_arr.mean())/img_arr.std()

In [ ]:
# Perform SVD using np.linalg.svd
U, S, VT = np.linalg.svd(img_arr_scaled)

In [ ]:
img_arr_scaled.shape, U.shape, S.shape, VT.shape    # m*n = m*m, m*n, n*n

## Reconstructing Image with top-K Singular vectors
- The top K singular vectors captures most of the variation. Therefore instead of using all the singular vectors and multiplying them as shown in SVD decomposition, we can reconstruct the image with top K singular vectors.

In [ ]:
# Let us use the top 5 singular vectors and reconstruct the matrix using matrix
# multiplication as shown above. Let us also visualize the reconstructed image.

nc = 5  # no of components
reconst_img_5 = U[:, :nc] @ np.diag(S[:nc]) @ VT[:nc, :]
plt.imshow(reconst_img_5)
plt.title("reconstructed image: 5 SVs")

In [ ]:
# let's use 50 SVs

nc = 50  # no of components
reconst_img_50 = U[:, :nc] @ np.diag(S[:nc]) @ VT[:nc, :]
plt.imshow(reconst_img_50)
plt.title("reconstructed image: 50 SVs")

In [ ]:
nc = 50  # no of components
reconst_img_100 = U[:, :nc] @ np.diag(S[:nc]) @ VT[:nc, :]
plt.imshow(reconst_img_100)
plt.title("reconstructed image: 100 SVs")


In [ ]:
nc = 1000  # no of components
reconst_img_1000 = U[:, :nc] @ np.diag(S[:nc]) @ VT[:nc, :]
plt.imshow(reconst_img_1000)
plt.title("reconstructed image: 1000 SVs")

- The quality of reconstructed image would improve as we use more top singular vectors. Here is a compraison of the reconstructed image using different number of top components.

In [ ]:
fig, axs = plt.subplots(2, 2,figsize=(10,10))
axs[0, 0].imshow(reconst_img_5)
axs[0, 0].set_title('Reconstructed Image: 5 SVs', size=16)
axs[0, 1].imshow(reconst_img_50)
axs[0, 1].set_title('Reconstructed Image: 50 SVs', size=16)
axs[1, 0].imshow(reconst_img_100)
axs[1, 0].set_title('Reconstructed Image: 100 SVs', size=16)
axs[1, 1].imshow(reconst_img_1000)
axs[1, 1].set_title('Reconstructed Image: 1000 SVs', size=16)
plt.tight_layout()

In [ ]:
plt.figure(figsize=(5,5))
plt.title("original r-band image")
plt.imshow(img_arr)

# Exercise

pd.crosstab()

In [ ]:
# for exercise
import pandas as pd
data = pd.DataFrame({'id': ['id1', 'id1', 'id1', 'id2', 'id2', 'id3'],
                  'fac_1': ['a', 'a', 'a', 'b', 'b', 'b'],
                  'fac_2': ['d', 'd', 'd', 'c', 'c', 'd']})
data

In [ ]:
pd.crosstab(data.fac_1, data.fac_2)

In [ ]:
pd.crosstab(data.id, data.fac_1)

In [ ]:
from collections import defaultdict  # provides a default value for a nonexistent key
x = defaultdict(lambda: [0.0, 0.0, 0.0, 0.0])

In [ ]:
x.items(), x.keys(), x.values(), x

In [ ]:
x['a'] = 'hello'

In [ ]:
x.items(), x.keys(), x.values(), x

In [ ]:
x_dict = {}   # regular dict
x_dict.items()

In [ ]:
from collections import defaultdict

# Example string
string = "default"

# Counting characters using defaultdict
char_count = defaultdict(int)
for char in string:
    char_count[char] += 1   # if None, the default (int) is 0

print(char_count)

In [ ]:
# Example string
string = "default"

# Counting characters using dict
char_count = {}
for char in string:
    if char in char_count:
        char_count[char] += 1
    else:
        char_count[char] = 1

print(char_count)

----------